name: Continuous Integration

on: pull_request

jobs:
  # The package provides a better algorithm for path-based filters.
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.2.0
        with:
          paths: '["**/*.rs", "Cargo.toml", "Cargo.lock", ".github/workflows/ci.yml"]'

  codestyle:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Installing rustfmt
        run: rustup component add rustfmt
      - name: Running rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  lint:
    needs: [codestyle]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Installing needed Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq libasound2-dev libssl-dev libpulse-dev libdbus-1-dev portaudio19-dev

      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Installing clippy
        run: rustup component add clippy
      - name: Linting project
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

  check:
    needs: [lint]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            features: portaudio_backend,rodio_backend,dbus_keyring
          - os: ubuntu-latest
            features: alsa_backend,rodio_backend,dbus_keyring,dbus_mpris

    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Installing macOS dependencies
        if: matrix.os == 'macos-latest'
        run: brew install pkg-config portaudio
      - name: Installing needed Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq libasound2-dev libssl-dev libpulse-dev libdbus-1-dev

      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Checking Rust code
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --no-default-features --features ${{ matrix.features }}
